//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace torrentloyunVera
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogKategori
    {
        public BlogKategori()
        {
            this.Bloglars = new HashSet<Bloglar>();
        }
    
        public int BlogKategoriİd { get; set; }
        public string BlogKategoriAdi { get; set; }
        public string BlogKategoriUrl { get; set; }
        public System.DateTime BlogKategoriTarih { get; set; }
    
        public virtual ICollection<Bloglar> Bloglars { get; set; }
    }
}
