//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace torrentloyunVera
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogYorum
    {
        public int BlogYorumİd { get; set; }
        public string BlogYorumYazi { get; set; }
        public string BlogYorumAdi { get; set; }
        public System.DateTime BlogTarih { get; set; }
        public string BlogEposta { get; set; }
        public bool BlogAkitf { get; set; }
        public int Blogİd { get; set; }
    
        public virtual Bloglar Bloglar { get; set; }
    }
}
