//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace torrentloyunVera
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Bloglars = new HashSet<Bloglar>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int Kullaniciİd { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciAdSoyad { get; set; }
        public System.DateTime KullaniciTarih { get; set; }
        public string KullaniciSifre { get; set; }
        public string KullaniciSifreTekrar { get; set; }
        public string KullaniciDogum { get; set; }
        public string KullaniciEposta { get; set; }
        public string KullaniciGuvenlik { get; set; }
        public bool KullaniciAktif { get; set; }
        public string KullaniciUrl { get; set; }
    
        public virtual ICollection<Bloglar> Bloglars { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
